# Generated by Django 4.0.2 on 2022-08-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxymodelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='type',
            field=models.CharField(choices=[('STUDENT', 'student'), ('TEACHER', 'teacher')], default='STUDENT', max_length=8),
        ),
    ]
