# Generated by Django 4.0.2 on 2022-08-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxymodelapp', '0002_useraccount_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('proxymodelapp.useraccount',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('proxymodelapp.useraccount',),
        ),
    ]
