# Generated by Django 4.0.2 on 2022-08-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxymodelapp', '0003_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(choices=[('STUDENT', 'student'), ('TEACHER', 'teacher')], default='TEACHER', max_length=8),
        ),
    ]
